leftnav:
- identifier: 0d7e54da-cafa-24a9-698f-871e243f26bb
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 2ab967d5-ea72-3c29-d6fa-b79255203346
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 3e6c0e77-5640-6a78-b916-f147c80b5ddb
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 7d382d92-561f-34c2-84d0-5daa5012ca10
  name: Labs
  url: /pages/labs
  weight: 40
